ENV_OVH_SMS_NOTIFY_NUMBERS = "OVH_SMS_NOTIFY_NUMBERS"  # comma-separated international numbers
ENV_OVH_SMS_SENDER_NAME = "OVH_SMS_SENDER_NAME"
ENV_OVH_SMS_SERVICE_NAME = "OVH_SMS_SERVICE_NAME"
ENV_OVH_SMS_USER_NAME = "OVH_SMS_USER_NAME"

ENV_OVH_API_APPLICATION_KEY = "OVH_API_APPLICATION_KEY"
ENV_OVH_API_APPLICATION_SECRET = "OVH_API_APPLICATION_SECRET"
ENV_OVH_API_CONSUMER_KEY = "OVH_API_CONSUMER_KEY"

ENV_MQTT_SERVER_HOST = "MQTT_SERVER_HOST"
ENV_MQTT_SERVER_PORT = "MQTT_SERVER_PORT"
ENV_MQTT_USER_NAME = "MQTT_USER_NAME"
ENV_MQTT_USER_PASSWORD = "MQTT_USER_PASSWORD"

ENV_MQTT_TLS_CIPHERS = "MQTT_TLS_CIPHERS"

DEFAULT_MQTT_TLS_CIPHERS = ("ECDHE-ECDSA-CHACHA20-POLY1305"
                            ":ECDHE-ECDSA-AES128-GCM-SHA256"
                            ":ECDHE-ECDSA-AES256-GCM-SHA384") # hand picked from `openssl ciphers`

DEFAULT_MQTT_TRANSPORT = "tcp"
DEFAULT_MQTT_KEEPALIVE_SECOND=60
DEFAULT_MQTT_CONNECT_TIMEOUT_SECOND=3

MQTT_APP = "gcn"
MQTT_APP_MANAGER_STATUS = f"{MQTT_APP}/manager/status"
MQTT_APP_MANAGER_STATUS_ONLINE = "online"
MQTT_APP_MANAGER_STATUS_OFFLINE = "offline"
MQTT_APP_MANAGER_SUBSCRIPTION = f"{MQTT_APP}/+/out/#"

MQTT_CLIENT_RANDOM_BYTES = 4
