# CLI options

CLI_OPT_TRACE = "--trace"

# mandatory parameters

ENV_MQTT_SERVER_HOST = "MQTT_SERVER_HOST"
ENV_MQTT_SERVER_PORT = "MQTT_SERVER_PORT"
ENV_MQTT_USER_NAME = "MQTT_USER_NAME"
ENV_MQTT_USER_PASSWORD = "MQTT_USER_PASSWORD"

# optional parameters

ENV_MQTT_TRANSPORT = "MQTT_TRANSPORT"
DEFAULT_MQTT_TRANSPORT = "tcp"

ENV_MQTT_TLS_MIN_VERSION = "MQTT_TLS_MIN_VERSION"
DEFAULT_MQTT_TLS_MIN_VERSION = None  # use python default for version

ENV_MQTT_TLS_MAX_VERSION = "MQTT_TLS_MAX_VERSION"
DEFAULT_MQTT_TLS_MAX_VERSION = None  # use python default for version

ENV_MQTT_TLS_CIPHERS = "MQTT_TLS_CIPHERS"
DEFAULT_MQTT_TLS_CIPHERS = None  # use python default for version

ENV_MQTT_KEEPALIVE_SECOND = "MQTT_KEEPALIVE_SECOND"
DEFAULT_MQTT_KEEPALIVE_SECOND = 60

ENV_MQTT_CONNECT_TIMEOUT_SECOND = "MQTT_CONNECT_TIMEOUT_SECOND"
DEFAULT_MQTT_CONNECT_TIMEOUT_SECOND = 3

ENV_MQTT_RECONNECT = "MQTT_RECONNECT"
DEFAULT_ENV_MQTT_RECONNECT = False

ENV_MQTT_IN_QUEUE_MAX_SIZE = "MQTT_IN_QUEUE_MAX_SIZE"
DEFAULT_MQTT_IN_QUEUE_MAX_SIZE = 1000

ENV_MQTT_LOG_LEVEL = "MQTT_LOG_LEVEL"
DEFAULT_MQTT_LOG_LEVEL = "warning"

ENV_MQTT_CLIENT_ID_RANDOM_BYTES = "MQTT_CLIENT_ID_RANDOM_BYTES"
DEFAULT_MQTT_CLIENT_ID_RANDOM_BYTES = 4

ENV_MQTT_SOCKET_SEND_BUFFER_SIZE = "MQTT_SOCKET_SEND_BUFFER_SIZE"
DEFAULT_MQTT_SOCKET_SEND_BUFFER_SIZE = 2 ** 11

ENV_GCN_IDLE_LOOP_SLEEP_MS = "GCN_IDLE_LOOP_SLEEP_MS"
DEFAULT_GCN_IDLE_LOOP_SLEEP_MS = 10 / 1000

ENV_GCN_NOTIFICATION_OUT_QUEUE_MAX_SIZE = "GCN_NOTIFICATION_OUT_QUEUE_MAX_SIZE"
DEFAULT_GCN_NOTIFICATION_OUT_QUEUE_MAX_SIZE = 100

# optional functions

ENV_SMS_NOTIFY_ENABLE = "SMS_NOTIFY_ENABLE"  # int, non zero = True, activates reasl sending of messages
ENV_SMS_NOTIFY_NUMBERS = "SMS_NOTIFY_NUMBERS"  # comma-separated international numbers: example 0033+9numbers in FR

ENV_OVH_SMS_SENDER_NAME = "OVH_SMS_SENDER_NAME"
ENV_OVH_SMS_SERVICE_NAME = "OVH_SMS_SERVICE_NAME"
ENV_OVH_SMS_USER_NAME = "OVH_SMS_USER_NAME"

## use autodetected env var names for OVH client
ENV_OVH_API_ENDPOINT_NAME = "OVH_ENDPOINT"
ENV_OVH_API_APPLICATION_KEY = "OVH_APPLICATION_KEY"
ENV_OVH_API_APPLICATION_SECRET = "OVH_APPLICATION_SECRET"
ENV_OVH_API_CONSUMER_KEY = "OVH_CONSUMER_KEY"

# hardcoded values

MQTT_APP = "gcn"

MQTT_APP_MANAGER = "manager"
MQTT_APP_MANAGER_STATUS = "status"
MQTT_APP_MANAGER_STATUS_ONLINE = "online"
MQTT_APP_MANAGER_STATUS_OFFLINE = "offline"
MQTT_APP_MANAGER_STATUS_TOPIC = f"{MQTT_APP}/{MQTT_APP_MANAGER}/{MQTT_APP_MANAGER_STATUS}"
MQTT_APP_MANAGER_STATUS_SUBSCRIPTION = f"{MQTT_APP_MANAGER_STATUS_TOPIC}/+"

MQTT_APP_CLIENT_OUT = "out"
MQTT_APP_CLIENT_SUBSCRIPTION = f"{MQTT_APP}/+/{MQTT_APP_CLIENT_OUT}/+"  # first level is where the good stuff is !
MQTT_APP_CLIENT_STATUS = "status"
MQTT_APP_CLIENT_MONITORED_GPIO="monitored_gpio"
MQTT_APP_CLIENT_HEARTBEAT="heartbeat_timestamp"
MQTT_APP_CLIENT_BUFFER_TOTAL_DROPPED_ITEM="buffer_total_dropped_item"


# MQTT_APP_CLIENT_OFFLINE_NOTIFICATION_AFTER_SECONDS=10*60 # TODO: notify
# MQTT_APP_CLIENT_OFFLINE_PURGE_AFTER_SECONDS=7*24*60*60 # TODO: PURGE
