
# mandatory parameters

ENV_MQTT_SERVER_HOST = "MQTT_SERVER_HOST"
ENV_MQTT_SERVER_PORT = "MQTT_SERVER_PORT"
ENV_MQTT_USER_NAME = "MQTT_USER_NAME"
ENV_MQTT_USER_PASSWORD = "MQTT_USER_PASSWORD"

# optional parameters

ENV_MQTT_TRANSPORT = "MQTT_TRANSPORT"
DEFAULT_MQTT_TRANSPORT = "tcp"

ENV_MQTT_TLS_CIPHERS = "MQTT_TLS_CIPHERS"
DEFAULT_MQTT_TLS_CIPHERS = ("ECDHE-ECDSA-CHACHA20-POLY1305"
                            ":ECDHE-ECDSA-AES128-GCM-SHA256"
                            ":ECDHE-ECDSA-AES256-GCM-SHA384") # hand picked from `openssl ciphers`

ENV_MQTT_KEEPALIVE_SECOND = "MQTT_KEEPALIVE_SECOND"
DEFAULT_MQTT_KEEPALIVE_SECOND=60

ENV_MQTT_CONNECT_TIMEOUT_SECOND="MQTT_CONNECT_TIMEOUT_SECOND"
DEFAULT_MQTT_CONNECT_TIMEOUT_SECOND=3

ENV_MQTT_RECONNECT="MQTT_RECONNECT"
DEFAULT_ENV_MQTT_RECONNECT=False

ENV_MQTT_IN_QUEUE_MAX_SIZE="MQTT_IN_QUEUE_MAX_SIZE"
DEFAULT_MQTT_IN_QUEUE_MAX_SIZE=1000

ENV_MQTT_LOG_LEVEL = "MQTT_LOG_LEVEL"
DEFAULT_MQTT_LOG_LEVEL = "warning"

ENV_MQTT_CLIENT_ID_RANDOM_BYTES="MQTT_CLIENT_ID_RANDOM_BYTES"
DEFAULT_MQTT_CLIENT_ID_RANDOM_BYTES = 4

ENV_GCN_IDLE_LOOP_SLEEP_MS="GCN_IDLE_LOOP_SLEEP_MS"
DEFAULT_GCN_IDLE_LOOP_SLEEP_MS=100


# optional functions

ENV_SMS_NOTIFY_NUMBERS = "SMS_NOTIFY_NUMBERS"  # comma-separated international numbers

ENV_OVH_SMS_SENDER_NAME = "OVH_SMS_SENDER_NAME"
ENV_OVH_SMS_SERVICE_NAME = "OVH_SMS_SERVICE_NAME"
ENV_OVH_SMS_USER_NAME = "OVH_SMS_USER_NAME"

ENV_OVH_API_APPLICATION_KEY = "OVH_API_APPLICATION_KEY"
ENV_OVH_API_APPLICATION_SECRET = "OVH_API_APPLICATION_SECRET"
ENV_OVH_API_CONSUMER_KEY = "OVH_API_CONSUMER_KEY"

# hardcoded values

ARG_TRACE = "--trace"

MQTT_APP = "gcn"
MQTT_APP_MANAGER_STATUS = f"{MQTT_APP}/manager/status"
MQTT_APP_MANAGER_STATUS_ONLINE = "online"
MQTT_APP_MANAGER_STATUS_OFFLINE = "offline"
MQTT_APP_MANAGER_SUBSCRIPTION = f"{MQTT_APP}/+/out/#"
